# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-23 08:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Benefits',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=200)),
                ('area_coverage', models.CharField(max_length=500, null=True)),
                ('basic_coverage', models.CharField(max_length=500, null=True)),
            ],
            options={
                'ordering': ('created',),
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=100, null=True)),
                ('eligibility', models.CharField(max_length=500, null=True)),
                ('area_coverage', models.CharField(max_length=500, null=True)),
                ('basic_coverage', models.CharField(max_length=500, null=True)),
            ],
            options={
                'ordering': ('created',),
            },
        ),
    ]
