# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-17 08:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cxa_query', '0002_auto_20170417_0714'),
    ]

    operations = [
        migrations.CreateModel(
            name='AreaCoverage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('area', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ('created',),
            },
        ),
        migrations.AddField(
            model_name='group',
            name='group_area_coverage',
            field=models.ForeignKey(blank=True, default=b'', null=True, on_delete=django.db.models.deletion.CASCADE, to='cxa_query.AreaCoverage'),
        ),
    ]
