# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-25 07:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cxa_query', '0002_admission'),
    ]

    operations = [
        migrations.RenameField(
            model_name='admission',
            old_name='after_admission',
            new_name='after_discharge',
        ),
        migrations.RenameField(
            model_name='admission',
            old_name='upon_admission',
            new_name='upon_discharge',
        ),
    ]
