# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-23 05:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cxa_query', '0002_auto_20170523_0355'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group',
            old_name='group_area_coverage',
            new_name='area_coverage',
        ),
        migrations.RenameField(
            model_name='group',
            old_name='group_basic_coverage',
            new_name='basic_coverage',
        ),
        migrations.RenameField(
            model_name='group',
            old_name='group_eligibility',
            new_name='eligibility',
        ),
    ]
