# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-17 08:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cxa_query', '0003_auto_20170417_0812'),
    ]

    operations = [
        migrations.CreateModel(
            name='BasicCoverage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('description', models.CharField(max_length=500)),
            ],
            options={
                'ordering': ('created',),
            },
        ),
        migrations.AddField(
            model_name='group',
            name='group_basic_coverage',
            field=models.ForeignKey(blank=True, default=b'', null=True, on_delete=django.db.models.deletion.CASCADE, to='cxa_query.BasicCoverage'),
        ),
    ]
