# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-25 08:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cxa_query', '0003_auto_20170525_0757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admission',
            name='after_discharge',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='admission',
            name='before_admission',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='admission',
            name='upon_discharge',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
