# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-23 05:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cxa_query', '0003_auto_20170523_0543'),
    ]

    operations = [
        migrations.CreateModel(
            name='Additional',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=200)),
                ('area_coverage', models.CharField(max_length=500, null=True)),
                ('basic_coverage', models.CharField(max_length=500, null=True)),
            ],
            options={
                'ordering': ('created',),
            },
        ),
    ]
