# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-26 01:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cxa_query', '0004_auto_20170525_0829'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=200)),
                ('details', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'ordering': ('created',),
            },
        ),
    ]
