# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-23 07:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cxa_query', '0004_additional'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Additional',
            new_name='Benefits',
        ),
    ]
