# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-24 03:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cxa_query', '0004_auto_20170417_0852'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='category',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
