# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-25 02:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cxa_query', '0005_group_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='areacoverage',
            old_name='area',
            new_name='description',
        ),
    ]
