# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-20 01:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cxa_query', '0007_auto_20170619_0307'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='claim_procedure',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='group',
            name='list_desc',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
