# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-20 01:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cxa_query', '0008_auto_20170620_0144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='area_coverage',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='group',
            name='basic_coverage',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='group',
            name='category',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='group',
            name='eligibility',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
