# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-20 03:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cxa_query', '0009_auto_20170620_0155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='basic_coverage',
            field=models.CharField(blank=True, max_length=3000, null=True),
        ),
    ]
